### ISSUE TITLE
可能会DNS泄露？

### ISSUE THREAD

**Issue by c-ujung** [217heidai/NestingDNS#15]
作者大佬你好，我用openclash设置所有dns到4053端口，也为smartdns的fq组配置了代理，使用ipleak.net检测会泄露出现国内的dns信息，相同配置如果使用默认的dns则不会有问题。

不知道是不是我配置的问题

**Comment by 217heidai** [comment]
当前mosdns的分流规则是会出现DNS泄漏，主要是为了兼顾访问效率。当前会先使用smartdns mainland组解析命中的国内域名，再使用smartdns gfw解析命中需要代理的域名，最后不在规则列表内的其它域名使用fallback模式进行解析，即同时使smartdns mainland、gfw解析并优先取国内IP，会导致不在规则列表内的域名解析出现DNS泄漏。  
```
      # mainland 域名解析
      - matches:
        - qname $geosite-cn
        exec: jump dns_mainland
      - matches: has_wanted_ans
        exec: accept
      
      # gfw 域名解析
      - matches:
        - qname $geosite-nocn
        exec: jump dns_gfw
      - matches: has_wanted_ans
        exec: accept
      
      # 其它域名解析
      - exec: $final_forward
```
改成先使用smartdns mainland组解析命中的国内域名，再使用smartdns gfw解析其它所有域名，能保证DNS不泄漏。但是会增加后续访问耗时，比如一个没有收录在国内域名列表的域名（但是有国外服务器或者CDN），或者一个不要代理的国外域名（但是有国内服务器或者CDN），通过smartdns gfw只能解析代理地的IP，会增加后续访问的耗时。  
```
      # mainland 域名解析
      - matches:
        - qname $geosite-cn
        exec: jump dns_mainland
      - matches: has_wanted_ans
        exec: accept
      
      # 其它域名解析
      - exec: jump dns_gfw
```
目前这是一个鱼和熊掌的问题。
